
spring:
  datasource:
     name: prod
     url: jdbc:mysql://47.92.252.92:3306/prod_che_heng_shi?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
     username: root
     password: 123456

wechatPay:
    appid: wx907c9c5582caeb09
    appsecret: 0b37c7b7996fed29cd528e1df509a896
    mch_id: 1521250771
    key: shenzhenchehengshiqichekeji20198
    notify_url: https://www.xcxht.chehengshi.com/order/wxNotify
    SIGNTYPE: MD5
    TRADETYPE: JSAPI
    pay_url: https://api.mch.weixin.qq.com/pay/unifiedorder
    filePathPrefix: /usr/java/log/demo/
    refund_url: https://api.mch.weixin.qq.com/secapi/pay/refund
    #dg123456.